#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VIEWER="$ROOT/app/src/main/java/kr/co/alldocuments/ui/DocumentViewer.kt"
GRADLE="$ROOT/app/build.gradle.kts"
HTML="$ROOT/app/src/main/assets/rhwp-viewer/index.html"

grep -q 'WebViewAssetLoader' "$VIEWER"
grep -q 'https://appassets.androidplatform.net/assets/rhwp-viewer/index.html' "$VIEWER"
grep -q 'androidx.webkit:webkit' "$GRADLE"
grep -q 'builtInZoomControls = true' "$VIEWER"
grep -q 'displayZoomControls = false' "$VIEWER"
grep -q 'setSupportZoom(true)' "$VIEWER"
grep -q 'onConsoleMessage' "$VIEWER"
grep -q 'onReceivedError' "$VIEWER"
grep -q 'RHWP 초기화 시간 초과' "$VIEWER"
grep -q 'canvasFontForMeasurement' "$HTML"
grep -q 'return font' "$HTML"
grep -q 'renderPageToCanvas' "$HTML"
grep -q 'canvas-page' "$HTML"
grep -q 'canvas.width' "$HTML"
grep -q 'canvas.height' "$HTML"
! grep -q 'renderPageSvg' "$HTML"
! grep -q 'normalizeSvg' "$HTML"
! grep -q 'text,.page svg tspan{font-family:.*!important' "$HTML"
! grep -q 'node.style.fontFamily=SYSTEM_FONT' "$HTML"
grep -q 'page-shell' "$HTML"
grep -q 'window.addEventListener.*error' "$HTML"
grep -q 'unhandledrejection' "$HTML"

echo "RHWP fixed-layout canvas integration test passed"
