#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VIEWER="$ROOT/app/src/main/java/kr/co/alldocuments/ui/DocumentViewer.kt"
GRADLE="$ROOT/app/build.gradle.kts"
HTML="$ROOT/app/src/main/assets/rhwp-viewer/index.html"

grep -q 'WebViewAssetLoader' "$VIEWER"
grep -q 'https://appassets.androidplatform.net/assets/rhwp-viewer/index.html' "$VIEWER"
grep -q 'androidx.webkit:webkit' "$GRADLE"
grep -q 'builtInZoomControls = true' "$VIEWER"
grep -q 'displayZoomControls = false' "$VIEWER"
grep -q 'setSupportZoom(true)' "$VIEWER"
grep -q 'onConsoleMessage' "$VIEWER"
grep -q 'onReceivedError' "$VIEWER"
grep -q 'RHWP 초기화 시간 초과' "$VIEWER"
grep -q 'SYSTEM_FONT' "$HTML"
grep -q 'normalizeCanvasFont' "$HTML"
grep -q 'page-shell' "$HTML"
grep -q 'text,tspan' "$HTML"
grep -q 'preserveAspectRatio' "$HTML"
grep -q 'viewBox' "$HTML"
grep -q 'removeAttribute.*width' "$HTML"
grep -q 'removeAttribute.*height' "$HTML"
grep -q 'window.addEventListener.*error' "$HTML"
grep -q 'unhandledrejection' "$HTML"

echo "RHWP WebView fidelity integration test passed"
